In [1]:
import torch

In [ ]:
torch.cuda.is_available()

In [8]:
x = torch.rand(5,3) # {0,1}
print(x)
print(x.dtype)

tensor([[0.8085, 0.0169, 0.7536],
        [0.2890, 0.0772, 0.9575],
        [0.7841, 0.1380, 0.3112],
        [0.9199, 0.6210, 0.9806],
        [0.3188, 0.5509, 0.9960]])
torch.float32


In [12]:
print((x - 0.5) * 2) # scale to -1 and 1

tensor([[ 3.0850, -4.8311,  2.5363],
        [-2.1104, -4.2276,  4.5746],
        [ 2.8411, -3.6201, -1.8882],
        [ 4.1987,  1.2103,  4.8062],
        [-1.8120,  0.5092,  4.9602]])


In [9]:
y = torch.ones(5,3, dtype=torch.int16)
print(y)
print(y.dtype)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
torch.int16


In [ ]:
torch.manual_seed(1157)
t1 = torch.rand(3,3)
t2 = torch.rand(3,3)
t3 = torch.rand(3,3)

In [11]:
print(2*y) # 2y : matrix*scalar
print(2*y + y - y - y) # 2y - y : matrix addition/subtraction 

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]], dtype=torch.int16)
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [16]:
u = (torch.rand(3, 3) - 0.5) * 2 # values between -1 and 1
print('A random matrix, r:')
print(u)

# Common mathematical operations are supported:
print('\nAbsolute value of r:')
print(torch.abs(u))

# ...as are trigonometric functions:
print('\nInverse sine of r:')
print(torch.asin(u))

# ...and linear algebra operations like determinant and singular value decomposition
print('\nDeterminant of r:')
print(torch.det(u))
print('\nSingular value decomposition of r:')
print(torch.svd(u))

# ...and statistical and aggregate operations:
print('\nAverage and standard deviation of r:')
print(torch.std_mean(u))
print('\nMaximum value of r:')
print(torch.max(u))

A random matrix, r:
tensor([[-0.6467,  0.4619,  0.5369],
        [ 0.7555,  0.2360, -0.9057],
        [ 0.4402, -0.3459,  0.5861]])

Absolute value of r:
tensor([[0.6467, 0.4619, 0.5369],
        [0.7555, 0.2360, 0.9057],
        [0.4402, 0.3459, 0.5861]])

Inverse sine of r:
tensor([[-0.7033,  0.4801,  0.5667],
        [ 0.8564,  0.2383, -1.1330],
        [ 0.4559, -0.3532,  0.6262]])

Determinant of r:
tensor(-0.4716)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.5796, -0.4361,  0.6884],
        [ 0.8082, -0.1995,  0.5541],
        [-0.1043,  0.8775,  0.4681]]),
S=tensor([1.4504, 0.8861, 0.3669]),
V=tensor([[ 0.6477,  0.5842,  0.4890],
        [-0.0282, -0.6231,  0.7817],
        [-0.7614,  0.5201,  0.3871]]))

Average and standard deviation of r:
(tensor(0.6005), tensor(0.1242))

Maximum value of r:
tensor(0.7555)
