In [1]:
### PyTorch Basics: Tensors & Gradient 01 ###

Looking in links: https://download.pytorch.org/whl/torch_stable.html


In [ ]:
## Install path
## !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

In [2]:
import torch

In [6]:
# Number
t1 = torch.tensor(4.) # by using 4., it creates a floating point number in a 1, size tensor
print(t1)
print(t1.dtype) # 4. is shorthand for 4.0, so the data_type is float 32-bit, rather than integer
print(t1.shape) # shape shows us the shape of the tensor

tensor(4.)
torch.float32
torch.Size([])


In [7]:
# 1D Tensor
t2 = torch.tensor([2., 3, 4, 5])
print(t2)
print(t2.shape)

tensor([2., 3., 4., 5.])
torch.Size([4])


In [9]:
# 2D / Matrix Tensor
t3 = torch.tensor([[1,2], [3,4], [5,6], [7,8]])
print(t3)
print(t3.shape)

# ! Tensors should have a regular shape / consistent shape - for example 
# t3 = torch.tensor([[1,2], [3,4], [5,6], [7,8,9]]) will pass an error
# conversely, a list of lists of lists would happily accept inconsistent internal vector lengths. This is one of...
# the key benefits / differences of tensors.

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])


In [13]:
# 3D Tensor
t4 = torch.tensor([
    [[11, 12, 13],
     [14, 15, 16]],
    [[17, 18, 19], 
     [20, 21, 22]]])
print(t4)
print(t4.shape)

tensor([[[11, 12, 13],
         [14, 15, 16]],

        [[17, 18, 19],
         [20, 21, 22]]])
torch.Size([2, 2, 3])


In [14]:
### Tensor Operations and Gradients ###

In [15]:
# create tensors
x = torch.tensor(3.)
y = torch.tensor(4., requires_grad=True)
z = torch.tensor(5., requires_grad=True)

In [18]:
a = x*y+z 

In [19]:
#What makes PyTorch unique is that we can automatically compute the derivative of 
# a w.r.t. the tensors that have requires_grad set to True i.e. y and z. 
# This feature of PyTorch is called autograd (automatic gradients).

# To compute the derivatives, we can invoke the .backward method on our result a

In [21]:
# compute derivative
a.backward()

In [22]:
# Display gradients
print('da/dx:', x.grad)
print('da/dy:', y.grad)
print('da/dz:', z.grad)

da/dx: None
da/dy: tensor(3.)
da/dz: tensor(1.)


In [ ]:
# As expected, da/dy has the same value as x, i.e., 3, and da/dz has the value 1. 
# Note that x.grad is None because x doesn't have requires_grad set to True.

# The "grad" in w.grad is short for gradient, which is another term for derivative. The term gradient is primarily used while dealing with vectors and matrices.
