In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


In [16]:
torch.cuda.is_available()

True

In [2]:
!nvidia-smi

Sun Jun 25 01:31:37 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 532.03                 Driver Version: 532.03       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080       WDDM | 00000000:0A:00.0  On |                  N/A |
|  0%   54C    P8               43W / 390W|    921MiB / 12288MiB |     11%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [4]:
# bracket notation helps to define the dimensions of a tensor in PyTorch
x = [[1, 2],[3, 4]]

In [5]:
x = torch.rand(5,3) # rand{0,1} 5 rows, 3 columns
print(x)
print(x.dtype)

tensor([[0.0147, 0.2303, 0.4586],
        [0.7209, 0.7244, 0.6453],
        [0.6382, 0.4942, 0.4240],
        [0.2419, 0.4693, 0.0804],
        [0.7046, 0.8142, 0.5757]])
torch.float32


#### Why random tensors?
Random tensors are important because many neural networks are initialized with random numbers, i.e. parameters weights and biases, and adjust these random numbers to better represent the data.

In [4]:
# Example of bracket notation and concept of a 3dim-tensor: 2D RGB image
random_image_tensor = torch.rand(size=(3, 1280, 720)) # RGB color channel, height (pixel), width (pixel)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 1280, 720]), 3)

In [ ]:
# Display random image
### Add code later ###

In [5]:
## Syntax notes ##
# torch.rand(X, Y, Z) == torch.rand(size=X, Y, Z), tensor of X * Y * Z dim

In [9]:
# Create a tensor of all zeros. 
zeros = torch.zeros(size=(3, 1280, 720))
zeros

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

#### Notes - Zero tensors
Zero tensors can function as a mask i.e. setting a column, row, etc, or the entire tensor of a target tensor to 0, using matrix mult.

In [10]:
# Using zero tensor as a mask
zeros*random_image_tensor # ... the same result as the zeros tensor above

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [12]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 1280, 720))
ones

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])

#### Notes - Random, Zeros and Ones tensors
In practice, random tensors are used a lot, so are zeros tensor. Less commonly one tensors are used. But it stands to reason that Ones and Zeros tensors together could be use in conjunction to create manually masks for sparse solutions to a deep learning neural network, or to specify a neural network connectivity (graph) matrix.


In [12]:
# Basic matrix operations
print((x - 0.5) * 2) # scale to -1 and 1

tensor([[ 3.0850, -4.8311,  2.5363],
        [-2.1104, -4.2276,  4.5746],
        [ 2.8411, -3.6201, -1.8882],
        [ 4.1987,  1.2103,  4.8062],
        [-1.8120,  0.5092,  4.9602]])


In [9]:
# Data types
y = torch.ones(5,3, dtype=torch.int16)
print(y)
print(y.dtype) # there are many torch datatypes. Torch tensors are strictly-typed like Numpy arrays.

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
torch.int16


In [ ]:
torch.manual_seed(1157)
t1 = torch.rand(3,3)
t2 = torch.rand(3,3)
t3 = torch.rand(3,3)

In [11]:
print(2*y) # 2y : matrix*scalar
print(2*y + y - y - y) # 2y - y : matrix addition/subtraction 

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]], dtype=torch.int16)
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [16]:
u = (torch.rand(3, 3) - 0.5) * 2 # values between -1 and 1
print('A random matrix, r:')
print(u)

# Common mathematical operations are supported:
print('\nAbsolute value of r:')
print(torch.abs(u))

# ...as are trigonometric functions:
print('\nInverse sine of r:')
print(torch.asin(u))

# ...and linear algebra operations like determinant and singular value decomposition
print('\nDeterminant of r:')
print(torch.det(u))
print('\nSingular value decomposition of r:')
print(torch.svd(u))

# ...and statistical and aggregate operations:
print('\nAverage and standard deviation of r:')
print(torch.std_mean(u))
print('\nMaximum value of r:')
print(torch.max(u))

A random matrix, r:
tensor([[-0.6467,  0.4619,  0.5369],
        [ 0.7555,  0.2360, -0.9057],
        [ 0.4402, -0.3459,  0.5861]])

Absolute value of r:
tensor([[0.6467, 0.4619, 0.5369],
        [0.7555, 0.2360, 0.9057],
        [0.4402, 0.3459, 0.5861]])

Inverse sine of r:
tensor([[-0.7033,  0.4801,  0.5667],
        [ 0.8564,  0.2383, -1.1330],
        [ 0.4559, -0.3532,  0.6262]])

Determinant of r:
tensor(-0.4716)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.5796, -0.4361,  0.6884],
        [ 0.8082, -0.1995,  0.5541],
        [-0.1043,  0.8775,  0.4681]]),
S=tensor([1.4504, 0.8861, 0.3669]),
V=tensor([[ 0.6477,  0.5842,  0.4890],
        [-0.0282, -0.6231,  0.7817],
        [-0.7614,  0.5201,  0.3871]]))

Average and standard deviation of r:
(tensor(0.6005), tensor(0.1242))

Maximum value of r:
tensor(0.7555)
