In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


In [2]:
torch.cuda.is_available()

True

In [3]:
!nvidia-smi

Wed Jun 28 22:21:26 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 532.03                 Driver Version: 532.03       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080       WDDM | 00000000:0A:00.0  On |                  N/A |
|  0%   48C    P8               43W / 390W|    823MiB / 12288MiB |     14%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [4]:
# bracket notation helps to define the dimensions of a tensor in PyTorch
x = [[1, 2],[3, 4]]

In [5]:
x = torch.rand(5,3) # rand{0,1} 5 rows, 3 columns
print(x)
print(x.dtype)

tensor([[0.5806, 0.8816, 0.8396],
        [0.1085, 0.0811, 0.8160],
        [0.9973, 0.8089, 0.7146],
        [0.0777, 0.6050, 0.0897],
        [0.3662, 0.8368, 0.4188]])
torch.float32


### Why random tensors?
Random tensors are important because many neural networks are initialized with random numbers, i.e. parameters weights and biases, and adjust these random numbers to better represent the data.

In [6]:
# Example of bracket notation and concept of a 3dim-tensor: 2D RGB image
random_image_tensor = torch.rand(size=(3, 1280, 720)) # RGB color channel, height (pixel), width (pixel)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 1280, 720]), 3)

In [7]:
# Display random image
### Add code later ###

In [8]:
## Syntax notes ##
# torch.rand(X, Y, Z) == torch.rand(size=X, Y, Z), tensor of X * Y * Z dim

In [9]:
# Create a tensor of all zeros. 
zeros = torch.zeros(size=(3, 1280, 720))
zeros

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

### Notes - Zero tensors
Zero tensors can function as a mask i.e. setting a column, row, etc, or the entire tensor of a target tensor to 0, using matrix mult.

In [10]:
# Using zero tensor as a mask
zeros*random_image_tensor # ... the same result as the zeros tensor above

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [11]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 1280, 720))
ones

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])

### Notes - Random, Zeros and Ones tensors
In practice, random tensors are used a lot, so are zeros tensor. Less commonly one tensors are used. But it stands to reason that Ones and Zeros tensors together could be use in conjunction to create manually masks for sparse solutions to a deep learning neural network, or to specify a neural network connectivity (graph) matrix.


In [19]:
# Use torch.arange(start, end 'end-1 index', step)
one_to_ten_tensor = torch.arange(1, 11)
print(one_to_ten_tensor)
ten_to_hundred_tensor = torch.arange(10, 101, 10) # == torch.arange(start=10, end=101, step=10)
print(ten_to_hundred_tensor)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])


In [28]:
# Creating tensors like e.g. zeros_like(input=X_tensor)
ten_zeros_tensor = torch.zeros_like(one_to_ten_tensor)
print(ten_zeros_tensor)
print(one_to_ten_tensor.shape)
print(ten_zeros_tensor.shape)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([10])
torch.Size([10])


In [57]:
# Tensor Datatypes
y1 = torch.ones(5,3, dtype=torch.int16)
y2 = torch.tensor([2.0, 4.0, 6.0, 8.0], 
               dtype=torch.int16, # What datatype the tensor is
               device="cuda", # What device is the tensor on i.e. select device "cpu", "gpu", "cuda", and so on...
               requires_grad=False) # Whether or not to track gradients with this tensor's operations
y3 = torch.tensor([2.0, 2.0, 4.0, 4.0], 
               dtype=torch.int32,
               device="cpu",
               requires_grad=False)
print(y1)
print(y1.dtype)
print()
print(y2)
print(y2.dtype)
print(y2.device)
print()
print(y3)
print(y3.dtype)
print(y3.device)
print()
print("Attempt y2*y3. Should throw an error due to different devices.")
try: print(y2*y3)
except Exception as e: print(e, ":O")

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
torch.int16

tensor([2, 4, 6, 8], device='cuda:0', dtype=torch.int16)
torch.int16
cuda:0

tensor([2, 2, 4, 4], dtype=torch.int32)
torch.int32
cpu

Attempt y2*y3. Should throw an error due to different devices.
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! :O


In [61]:
# Changing a datatype
float_double_y2 = y2.type(torch.double) # == y2.type(torch.float64)
print(float_double_y2)
print(float_double_y2.shape, float_double_y2.size())

tensor([2., 4., 6., 8.], device='cuda:0', dtype=torch.float64)
torch.Size([4]) torch.Size([4])


### Notes - Tensor Data Types
There are many torch datatypes. Torch tensors are strictly-typed like Numpy arrays.
Refer to https://pytorch.org/docs/stable/tensors.html#torch-tensor for datatypes.
Recall the level of precision or max-min trade-off for the bit-size a datatype requires
Running a deep learning neural network on a smaller bit-size datatypes typically will be faster, so this embodies the precision vs. speed trade-off.


### Common sources of errors (check tensor attributes)
1. Tensors are not the correct/compatible datatype - check tensor.dtype
2. Tensors are not the correct shape - check tensor.shape (== tensor.size(), a method)
e.g. m x n * n x p shape required for matrix mult 
3. Tensors are not on the right device - check tensor.device
e.g. one tensor is on the "cpu" and another is on the "gpu", and you attempt to perform a matrix operation between these two tensors 

## Manipulating Tensors (Tensor operations)
Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [62]:
# Basic matrix operations
z = y - 0.5
print(z)
print((z - 0.5) * 2) # scale to -1 and 1 from {0,1} range 
#i.e. 0.5 on the range {0, 1} changes to 0 in range {-1,1}

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [63]:
torch.manual_seed(1157)
t1 = torch.rand(3,3)
t2 = torch.rand(3,3)
t3 = torch.rand(3,3)

In [11]:
print(2*z) # 2y : matrix*scalar
print(2*z + z - z - z) # 2z - z : matrix addition/subtraction 

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]], dtype=torch.int16)
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [90]:
print(f" z: {z}")
print(z.shape)
t4 = torch.rand(5,3)
print(f" t4: {t4}")
print(t4.shape)
t5 = torch.rand(3,5)
print(f" t5: {t5}")
print(t5.shape)
print(f" element-wise mult, z * t4: {z * t4}")
print("element-wise mult simply halves the entries of t4 because z is 0.5 in all entries")
print(f" mat-mult (dot product) z * t5: {torch.matmul(z, t5)}")
print("matrix multiplication (dot product) performs, in a 2D case, a row by col element-wise mult then summation ... ")
print("... for each entry in the result. E.g. the 1,1 entry is the element-wise multiplication and summation of...")
print("... the first row of the first tensor and the first column of the second tensor.")

 z: tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])
torch.Size([5, 3])
 t4: tensor([[0.2693, 0.9987, 0.4954],
        [0.5404, 0.8359, 0.7370],
        [0.8326, 0.0146, 0.3511],
        [0.9076, 0.2586, 0.2114],
        [0.9079, 0.0068, 0.7574]])
torch.Size([5, 3])
 t5: tensor([[0.1269, 0.9468, 0.3391, 0.8739, 0.3752],
        [0.9810, 0.8429, 0.3275, 0.1366, 0.8235],
        [0.7632, 0.1902, 0.6937, 0.6986, 0.6828]])
torch.Size([3, 5])
 element-wise mult, z * t4: tensor([[0.1346, 0.4993, 0.2477],
        [0.2702, 0.4179, 0.3685],
        [0.4163, 0.0073, 0.1756],
        [0.4538, 0.1293, 0.1057],
        [0.4539, 0.0034, 0.3787]])
element-wise mult simply halves the entries of t4 because z is 0.5 in all entries
 mat-mult (dot product) z * t5: tensor([[0.9356, 0.9899, 0.6802, 0.8546, 0.9408],
        [0.9356, 0.9899, 0.6802, 0.8546, 0.9408],
        [0.9356, 0.9899

In [99]:
tensor_a = z
tensor_b = t5

In [100]:
%%time
torch.matmul(tensor_a, tensor_b)

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[0.9356, 0.9899, 0.6802, 0.8546, 0.9408],
        [0.9356, 0.9899, 0.6802, 0.8546, 0.9408],
        [0.9356, 0.9899, 0.6802, 0.8546, 0.9408],
        [0.9356, 0.9899, 0.6802, 0.8546, 0.9408],
        [0.9356, 0.9899, 0.6802, 0.8546, 0.9408]])

In [127]:
%%time
#np_array = np.array([])
for row_i in tensor_a:
    for col_j in torch.t(tensor_b):
        print((torch.sum(row_i*col_j).item()))
#print(np_array)

0.9355508089065552
0.9899342060089111
0.6801728010177612
0.8545556664466858
0.9407556653022766
0.9355508089065552
0.9899342060089111
0.6801728010177612
0.8545556664466858
0.9407556653022766
0.9355508089065552
0.9899342060089111
0.6801728010177612
0.8545556664466858
0.9407556653022766
0.9355508089065552
0.9899342060089111
0.6801728010177612
0.8545556664466858
0.9407556653022766
0.9355508089065552
0.9899342060089111
0.6801728010177612
0.8545556664466858
0.9407556653022766
CPU times: total: 0 ns
Wall time: 1.22 ms


In [106]:
u = (torch.rand(3, 3) - 0.5) * 2 # scale values between -1 and 1
print('A random matrix, r:')
print(u)

# Common mathematical operations are supported:
print('\nAbsolute value of r:')
print(torch.abs(u))

# ...as are trigonometric functions:
print('\nInverse sine of r:')
print(torch.asin(u))

# ...and linear algebra operations like determinant and singular value decomposition
print('\nDeterminant of r:')
print(torch.det(u))
print('\nSingular value decomposition of r:')
print(torch.svd(u))

# ...and statistical and aggregate operations:
print('\nAverage and standard deviation of r:')
print(torch.std_mean(u))
print('\nMaximum value of r:')
print(torch.max(u))

A random matrix, r:
tensor([[-0.7493, -0.5483, -0.5114],
        [-0.3329, -0.5414, -0.9961],
        [-0.3848, -0.7838, -0.0341]])

Absolute value of r:
tensor([[0.7493, 0.5483, 0.5114],
        [0.3329, 0.5414, 0.9961],
        [0.3848, 0.7838, 0.0341]])

Inverse sine of r:
tensor([[-0.8469, -0.5803, -0.5368],
        [-0.3394, -0.5721, -1.4824],
        [-0.3950, -0.9008, -0.0341]])

Determinant of r:
tensor(0.3403)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.6185,  0.1591, -0.7695],
        [-0.6622, -0.6327,  0.4014],
        [-0.4230,  0.7578,  0.4967]]),
S=tensor([1.6604, 0.6545, 0.3132]),
V=tensor([[ 0.5099, -0.3058,  0.8040],
        [ 0.6199, -0.5174, -0.5899],
        [ 0.5964,  0.7992, -0.0743]]))

Average and standard deviation of r:
(tensor(0.2817), tensor(-0.5425))

Maximum value of r:
tensor(-0.0341)
